name: Nix Powered Tests

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
    - run: |
        nix develop -c bash<<SH
          bundle install
          bundle exec rspec
        SH
